typography_spectrum: 0.6731315786018968
content_rating:
  adult: false
color:
  brandStrength: 0.7088345575612038
  lightness: 0.4223091099411249
  saturation: 0.30451712757349014
  rhythmicContrast: 0.3304271448869258
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.8835618675220758
author:
  name: ddddddddd
name: othrstss
navigation:
  - name: >-
      New SpaceX landing photos make you feel like the rocket is coming down on
      top of you
    id: 10b16c53-e7de-42e5-9b71-4e49c1019e13
    type: content
title: Mjrio
description: marsch.js@gmail.co
