typography_spectrum: 0.6731315786018968
content_rating:
  adult: false
color:
  brandStrength: 0.7088345575612038
  lightness: 0.4223091099411249
  saturation: 0.30451712757349014
  rhythmicContrast: 0.3304271448869258
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.8835618675220758
author:
  name: ddddddddd
name: othrstss
navigation:
  - name: super ddduper
    url: 'https://github.com/facebook/immutable-js/issues/732'
    type: external
  - name: p2sasdfs
    id: cfc39499-8276-418e-9cbd-7cba8b8ed400
    type: content
title: Mjrio
description: marsch.js@gmail.co
