typography_spectrum: 0.6731315786018968
content_rating:
  adult: false
color:
  brandStrength: 0.7088345575612038
  lightness: 0.4223091099411249
  saturation: 0.30451712757349014
  rhythmicContrast: 0.3304271448869258
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.8835618675220758
profiles: []
author:
  name: ddddddddd
name: othrstss
navigation:
  - name: asdfasdfa1
    id: ef7797ba-0e6c-405d-bb62-03af0afd3ef5
    type: content
  - name: 'Interview: Artist Ryan McGinness on Designing for Hennessy'
    id: 7dd770b1-ba59-4bc6-9949-6398fdbf9567
    type: content
title: "\uD83D\uDE02Mdd\uD83D\uDE02jrio"
description: marsch.js@gmail.co
