typography_spectrum: 0.6731315786018968
color:
  brandStrength: 0.7088345575612038
  lightness: 0.4223091099411249
  saturation: 0.30451712757349014
  rhythmicContrast: 0.3304271448869258
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.8835618675220758
name: asdfasdf
navigation:
  - id: 4365df1b-ffe6-4f95-be37-59550c2f66dc
    name: saw
    type: content
title: >-
  Incidents should be classified as they are recorded, Examples of incidents by
  classification are:<br>Application<br>service not available<br>data
  issue<br>application bug<br>Report not coming up<br>Excel not
  downloading<br>disk-usage threshold exceeded<br>Hardware<br>
description: adsf
