typography_spectrum: 0.6731315786018968
content_rating:
  adult: false
color:
  brandStrength: 0.7088345575612038
  lightness: 0.4223091099411249
  saturation: 0.30451712757349014
  rhythmicContrast: 0.3304271448869258
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.8835618675220758
profiles:
  - id: 7a53608a-396e-4d5b-9943-a68fdcc6e9db
    name: 'Best of CH 2015: Instagram'
    type: content
    rel: footer
  - url: 'http://asdfasdf.com'
    name: asdvsdf
    type: external
    rel: footer
  - id: d3ce2425-23ad-4440-85b6-e1bbfadc1d5c
    name: 'Drinks: Smoked Manhattan'
    type: content
    rel: footer
author:
  name: ddddddddd
name: othrstss
navigation:
  - name: asdfasdfa1
    id: ef7797ba-0e6c-405d-bb62-03af0afd3ef5
    type: content
title: Mddjrio
description: marsch.js@gmail.co
