typography_spectrum: 0.6731315786018968
content_rating:
  adult: false
color:
  brandStrength: 0.7088345575612038
  lightness: 0.4223091099411249
  saturation: 0.30451712757349014
  rhythmicContrast: 0.3304271448869258
  brandColors:
    - '#2F2933'
    - '#01A2A6'
    - '#29D9C2'
    - '#BDF271'
    - '#FFFFA6'
layout_spectrum: 0.8835618675220758
author:
  name: ddddddddd
name: 'null'
navigation:
  - name: UPSIDdddEDOWN
    id: 4365df1b-ffe6-4f95-be37-59550c2f66dc
    type: content
  - name: UPSIDdddEDOWN
    id: 66aa1986-c9ec-4556-9239-8c9177fb4168
    type: content
  - name: cccc
    url: 'http://www.google.de'
    type: external
  - name: UPSIDdddEDOWN
    id: 865b0e4a-7e80-44da-a9d7-7ef0b961c9f8
    type: content
title: undddined
description: undefined
